import type { Context, Config } from "@netlify/functions";

/**
 * Integration Hub — Prepares and routes pipeline data to external systems.
 * Currently stubbed for Wrike and McKinsey WAVE.
 *
 * When endpoints become available:
 * 1. Set env vars: WRIKE_API_TOKEN, WRIKE_BASE_URL, WAVE_API_KEY, WAVE_BASE_URL
 * 2. Uncomment the actual API call blocks below
 * 3. Redeploy
 */

// ─── Types ──────────────────────────────────────────────────────────────────

interface PipelineData {
  id?: string;
  intake: string;
  refined?: string;
  prd?: string;
  tech_spec?: string;
  estimate?: string;
  proto_prompt?: string;
  build_status?: string;
  current_stage: number;
}

interface IntegrationRequest {
  target: "wrike" | "wave" | "jellyfish" | "status";
  action: string;
  pipeline: PipelineData;
}

interface IntegrationStatus {
  wrike:     { configured: boolean; connected: boolean; base_url: string | null };
  wave:      { configured: boolean; connected: boolean; base_url: string | null };
  jellyfish: { configured: boolean; connected: boolean; base_url: string | null };
}

// ─── Wrike Payload Builders ─────────────────────────────────────────────────

/**
 * Maps pipeline data to Wrike project/task structure.
 * Wrike API docs: https://developers.wrike.com/api/v4/
 *
 * Expected Wrike env vars:
 *   WRIKE_API_TOKEN  — OAuth2 permanent token or bearer token
 *   WRIKE_BASE_URL   — e.g., https://www.wrike.com/api/v4 (default)
 *   WRIKE_FOLDER_ID  — (optional) parent folder to create projects in
 */
function buildWrikeProject(pipeline: PipelineData) {
  const projectTitle = pipeline.intake.split("\n")[0].slice(0, 80) || "Product Forge Pipeline";
  return {
    // POST /folders/{folderId}/folders  — creates a project
    create_project: {
      title: projectTitle,
      description: `Generated by Product Forge AI\n\nOriginal Intake:\n${pipeline.intake}`,
      project: {
        status: "Green",
        startDate: new Date().toISOString().split("T")[0],
      },
      customFields: [],
      metadata: [{ key: "source", value: "product-forge-ai" }],
    },
    // POST /folders/{projectId}/tasks  — creates tasks from pipeline stages
    tasks: [
      ...(pipeline.refined ? [{
        title: "Refined Product Definition",
        description: pipeline.refined,
        status: "Completed",
        importance: "High",
      }] : []),
      ...(pipeline.prd ? [{
        title: "Product Requirements Document (PRD)",
        description: pipeline.prd,
        status: "Completed",
        importance: "High",
      }] : []),
      ...(pipeline.tech_spec ? [{
        title: "Technical Specification",
        description: pipeline.tech_spec,
        status: "Completed",
        importance: "High",
      }] : []),
      ...(pipeline.estimate ? [{
        title: "Cost & Timeline Estimate",
        description: pipeline.estimate,
        status: "Completed",
        importance: "High",
      }] : []),
      // Placeholder follow-up tasks
      { title: "Review & Approve PRD", status: "Active", importance: "High" },
      { title: "Vendor/Team Selection", status: "Active", importance: "Normal" },
      { title: "Kick-off Meeting", status: "Deferred", importance: "Normal" },
    ],
  };
}

/**
 * Sends data to Wrike API.
 * STUBBED — uncomment when WRIKE_API_TOKEN is available.
 */
async function pushToWrike(pipeline: PipelineData): Promise<{ success: boolean; message: string; payload: any }> {
  const token = Netlify.env.get("WRIKE_API_TOKEN");
  const baseUrl = Netlify.env.get("WRIKE_BASE_URL") || "https://www.wrike.com/api/v4";
  const folderId = Netlify.env.get("WRIKE_FOLDER_ID");

  const payload = buildWrikeProject(pipeline);

  if (!token) {
    return {
      success: false,
      message: "Wrike integration not configured. Set WRIKE_API_TOKEN environment variable.",
      payload, // Return the payload so the user can see what WOULD be sent
    };
  }

  /* ── UNCOMMENT WHEN READY ──────────────────────────────────────────────
  try {
    // Step 1: Create project folder
    const projectRes = await fetch(`${baseUrl}/folders/${folderId}/folders`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload.create_project),
    });

    if (!projectRes.ok) {
      const err = await projectRes.text();
      return { success: false, message: `Wrike API error: ${err}`, payload };
    }

    const projectData = await projectRes.json();
    const projectId = projectData.data?.[0]?.id;

    // Step 2: Create tasks within the project
    for (const task of payload.tasks) {
      await fetch(`${baseUrl}/folders/${projectId}/tasks`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(task),
      });
    }

    return {
      success: true,
      message: `Project created in Wrike (ID: ${projectId}) with ${payload.tasks.length} tasks.`,
      payload,
    };
  } catch (e: any) {
    return { success: false, message: `Wrike connection error: ${e.message}`, payload };
  }
  ── END UNCOMMENT ──────────────────────────────────────────────────────── */

  return {
    success: false,
    message: "Wrike integration is configured but the API call is currently stubbed. Uncomment the API block in integrations.mts to enable.",
    payload,
  };
}

// ─── McKinsey WAVE Payload Builders ─────────────────────────────────────────

/**
 * Maps pipeline data to McKinsey WAVE initiative structure.
 * WAVE is used for value creation planning and transformation tracking.
 *
 * Expected WAVE env vars:
 *   WAVE_API_KEY    — API key or OAuth token
 *   WAVE_BASE_URL   — WAVE API endpoint (to be provided by McKinsey)
 *   WAVE_PROGRAM_ID — (optional) parent program/portfolio ID
 *
 * NOTE: WAVE API schema is assumed based on typical transformation
 * management platforms. Adjust field mappings when actual API docs are available.
 */
function buildWaveInitiative(pipeline: PipelineData) {
  const initiativeName = pipeline.intake.split("\n")[0].slice(0, 80) || "Product Forge Initiative";

  // Extract cost estimates from the estimate text if available
  const estimateText = pipeline.estimate || "";
  const costMatch = estimateText.match(/\$[\d,.]+[KkMm]?\s*[-–]\s*\$[\d,.]+[KkMm]?/);
  const timelineMatch = estimateText.match(/(\d+)\s*[-–]\s*(\d+)\s*weeks/i);

  return {
    // Initiative creation payload
    initiative: {
      name: initiativeName,
      description: pipeline.refined || pipeline.intake,
      source: "product-forge-ai",
      status: pipeline.current_stage >= 5 ? "ready_for_review" : "in_development",
      category: "digital_transformation",
      created_date: new Date().toISOString(),
    },
    // Value drivers / business case
    business_case: {
      problem_statement: pipeline.intake,
      refined_scope: pipeline.refined || null,
      requirements_summary: pipeline.prd || null,
      technical_approach: pipeline.tech_spec || null,
      cost_estimate_raw: pipeline.estimate || null,
      estimated_cost_range: costMatch ? costMatch[0] : null,
      estimated_timeline_weeks: timelineMatch ? `${timelineMatch[1]}-${timelineMatch[2]}` : null,
    },
    // Deliverables / artifacts
    artifacts: [
      ...(pipeline.refined ? [{ type: "product_definition", content: pipeline.refined, stage: "refinement" }] : []),
      ...(pipeline.prd ? [{ type: "prd", content: pipeline.prd, stage: "requirements" }] : []),
      ...(pipeline.tech_spec ? [{ type: "technical_spec", content: pipeline.tech_spec, stage: "architecture" }] : []),
      ...(pipeline.estimate ? [{ type: "cost_estimate", content: pipeline.estimate, stage: "estimation" }] : []),
      ...(pipeline.proto_prompt ? [{ type: "prototype_prompt", content: pipeline.proto_prompt, stage: "prototyping" }] : []),
    ],
    // Impact assessment placeholder
    impact: {
      value_at_stake: null, // To be filled by WAVE users
      confidence_level: pipeline.current_stage >= 5 ? "medium" : "low",
      time_to_value_weeks: timelineMatch ? parseInt(timelineMatch[2]) : null,
    },
  };
}

/**
 * Sends data to McKinsey WAVE API.
 * STUBBED — uncomment when WAVE_API_KEY and WAVE_BASE_URL are available.
 */
async function pushToWave(pipeline: PipelineData): Promise<{ success: boolean; message: string; payload: any }> {
  const apiKey = Netlify.env.get("WAVE_API_KEY");
  const baseUrl = Netlify.env.get("WAVE_BASE_URL");
  const programId = Netlify.env.get("WAVE_PROGRAM_ID");

  const payload = buildWaveInitiative(pipeline);

  if (!apiKey || !baseUrl) {
    return {
      success: false,
      message: "McKinsey WAVE integration not configured. Set WAVE_API_KEY and WAVE_BASE_URL environment variables.",
      payload,
    };
  }

  /* ── UNCOMMENT WHEN READY ──────────────────────────────────────────────
  try {
    const endpoint = programId
      ? `${baseUrl}/programs/${programId}/initiatives`
      : `${baseUrl}/initiatives`;

    // Step 1: Create initiative
    const initRes = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
        "X-Source": "product-forge-ai",
      },
      body: JSON.stringify(payload.initiative),
    });

    if (!initRes.ok) {
      const err = await initRes.text();
      return { success: false, message: `WAVE API error: ${err}`, payload };
    }

    const initData = await initRes.json();
    const initiativeId = initData.id;

    // Step 2: Attach business case
    await fetch(`${baseUrl}/initiatives/${initiativeId}/business-case`, {
      method: "PUT",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload.business_case),
    });

    // Step 3: Upload artifacts
    for (const artifact of payload.artifacts) {
      await fetch(`${baseUrl}/initiatives/${initiativeId}/artifacts`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(artifact),
      });
    }

    return {
      success: true,
      message: `Initiative created in WAVE (ID: ${initiativeId}) with ${payload.artifacts.length} artifacts.`,
      payload,
    };
  } catch (e: any) {
    return { success: false, message: `WAVE connection error: ${e.message}`, payload };
  }
  ── END UNCOMMENT ──────────────────────────────────────────────────────── */

  return {
    success: false,
    message: "WAVE integration is configured but the API call is currently stubbed. Uncomment the API block in integrations.mts to enable.",
    payload,
  };
}

// ─── Jellyfish Engineering Intelligence ──────────────────────────────────────

/**
 * Pulls engineering metrics from Jellyfish to inform cost estimates.
 * Jellyfish API docs: https://app.jellyfish.co (contact api@jellyfish.co)
 *
 * Expected env vars:
 *   JELLYFISH_API_TOKEN  — API token (Authorization: Token <token>)
 *   JELLYFISH_BASE_URL   — e.g., https://app.jellyfish.co (default)
 *
 * Data pulled:
 *   - Team allocations (where engineering time is spent)
 *   - Delivery velocity (epics/deliverables throughput)
 *   - Developer productivity metrics (cycle time, PR throughput)
 */

interface JellyfishMetrics {
  allocations: any | null;
  delivery: any | null;
  metrics: any | null;
  fetched_at: string;
}

async function jellyfishFetch(path: string, token: string, baseUrl: string): Promise<any> {
  const res = await fetch(`${baseUrl}${path}`, {
    headers: {
      "Authorization": `Token ${token}`,
      "Content-Type": "application/json",
      "Accept": "application/json",
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Jellyfish API ${res.status}: ${text}`);
  }
  return res.json();
}

async function pullFromJellyfish(): Promise<{ success: boolean; message: string; data: JellyfishMetrics | null }> {
  const token = Netlify.env.get("JELLYFISH_API_TOKEN");
  const baseUrl = Netlify.env.get("JELLYFISH_BASE_URL") || "https://app.jellyfish.co";

  if (!token) {
    return {
      success: false,
      message: "Jellyfish integration not configured. Set JELLYFISH_API_TOKEN environment variable. Contact api@jellyfish.co for API access.",
      data: null,
    };
  }

  try {
    // Calculate timeframe: last 3 months
    const now = new Date();
    const threeMonthsAgo = new Date(now);
    threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
    const startParam = `${threeMonthsAgo.toLocaleString("en-US", { month: "short" })}-${String(threeMonthsAgo.getFullYear()).slice(2)}`;
    const endParam = `${now.toLocaleString("en-US", { month: "short" })}-${String(now.getFullYear()).slice(2)}`;

    // Fetch data in parallel from three domains
    const [allocations, delivery, metrics] = await Promise.allSettled([
      jellyfishFetch(
        `/endpoints/export/v0/allocations/summary?timeframe=${startParam}&end=${endParam}`,
        token, baseUrl
      ),
      jellyfishFetch(
        `/endpoints/export/v0/delivery/work_category_contents?work_category_slug=epics&timeframe=${startParam}&end=${endParam}`,
        token, baseUrl
      ),
      jellyfishFetch(
        `/endpoints/export/v0/metrics/team_summary?timeframe=${startParam}&end=${endParam}`,
        token, baseUrl
      ),
    ]);

    const data: JellyfishMetrics = {
      allocations: allocations.status === "fulfilled" ? allocations.value : null,
      delivery: delivery.status === "fulfilled" ? delivery.value : null,
      metrics: metrics.status === "fulfilled" ? metrics.value : null,
      fetched_at: now.toISOString(),
    };

    const successCount = [allocations, delivery, metrics].filter(r => r.status === "fulfilled").length;

    return {
      success: successCount > 0,
      message: successCount === 3
        ? `Successfully fetched all Jellyfish data (allocations, delivery, metrics) for ${startParam} to ${endParam}.`
        : `Partially fetched Jellyfish data (${successCount}/3 endpoints succeeded) for ${startParam} to ${endParam}.`,
      data,
    };
  } catch (e: any) {
    return { success: false, message: `Jellyfish connection error: ${e.message}`, data: null };
  }
}

/**
 * Formats Jellyfish data into a context block that can be injected into
 * the Estimate stage prompt to ground cost projections in real engineering data.
 */
function formatJellyfishContext(data: JellyfishMetrics): string {
  const sections: string[] = [];

  sections.push("## Real Engineering Data from Jellyfish\n");
  sections.push("The following data comes from your organization's Jellyfish engineering intelligence platform.");
  sections.push("Use this data to ground your estimates in actual team performance rather than industry averages.\n");

  if (data.allocations) {
    sections.push("### Team Allocation Data");
    sections.push("```json");
    sections.push(JSON.stringify(data.allocations, null, 2).slice(0, 3000));
    sections.push("```\n");
  }

  if (data.delivery) {
    sections.push("### Delivery Velocity (Epics/Deliverables)");
    sections.push("```json");
    sections.push(JSON.stringify(data.delivery, null, 2).slice(0, 3000));
    sections.push("```\n");
  }

  if (data.metrics) {
    sections.push("### Team Performance Metrics (DORA/Productivity)");
    sections.push("```json");
    sections.push(JSON.stringify(data.metrics, null, 2).slice(0, 3000));
    sections.push("```\n");
  }

  sections.push(`*Data fetched: ${data.fetched_at}*`);

  return sections.join("\n");
}

// ─── Status Check ───────────────────────────────────────────────────────────

function getIntegrationStatus(): IntegrationStatus {
  return {
    wrike: {
      configured: !!Netlify.env.get("WRIKE_API_TOKEN"),
      connected: false,
      base_url: Netlify.env.get("WRIKE_BASE_URL") || "https://www.wrike.com/api/v4",
    },
    wave: {
      configured: !!(Netlify.env.get("WAVE_API_KEY") && Netlify.env.get("WAVE_BASE_URL")),
      connected: false,
      base_url: Netlify.env.get("WAVE_BASE_URL") || null,
    },
    jellyfish: {
      configured: !!Netlify.env.get("JELLYFISH_API_TOKEN"),
      connected: false,
      base_url: Netlify.env.get("JELLYFISH_BASE_URL") || "https://app.jellyfish.co",
    },
  };
}

// ─── Handler ────────────────────────────────────────────────────────────────

export default async (req: Request, context: Context) => {
  const headers = { "Content-Type": "application/json" };

  // GET — return integration status
  if (req.method === "GET") {
    return new Response(JSON.stringify(getIntegrationStatus()), { headers });
  }

  // POST — push to integration
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405, headers });
  }

  let body: IntegrationRequest;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON" }), { status: 400, headers });
  }

  const { target, pipeline } = body;

  if (!pipeline) {
    return new Response(JSON.stringify({ error: "Pipeline data is required" }), { status: 400, headers });
  }

  let result;
  switch (target) {
    case "wrike":
      result = await pushToWrike(pipeline);
      break;
    case "wave":
      result = await pushToWave(pipeline);
      break;
    case "jellyfish":
      const jfResult = await pullFromJellyfish();
      // Return data + formatted context for the estimate prompt
      result = {
        success: jfResult.success,
        message: jfResult.message,
        payload: jfResult.data,
        context: jfResult.data ? formatJellyfishContext(jfResult.data) : null,
      };
      break;
    case "status":
      return new Response(JSON.stringify(getIntegrationStatus()), { headers });
    default:
      return new Response(JSON.stringify({ error: `Unknown target: ${target}` }), { status: 400, headers });
  }

  return new Response(JSON.stringify(result), {
    status: result.success ? 200 : 202, // 202 = accepted but not processed (stub)
    headers,
  });
};

export const config: Config = {
  path: "/api/integrations",
};
